# Generated by Django 4.2.7 on 2023-12-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(max_length=100, verbose_name="Department Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Student Id"
                    ),
                ),
                ("student_name", models.CharField(max_length=240, verbose_name="Name")),
                ("email", models.EmailField(max_length=254)),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                ("address", models.TextField(verbose_name="Address")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.department"
                    ),
                ),
            ],
        ),
    ]
